// Los 23 ejercicios del prototipo (docs/referencia/hora-muerta-modos.html, GYM_ITEMS y
// GYM_ANS), portados literalmente. Las respuestas van en forma de autor (salas por id,
// personas por nombre, objetos por clave) y scripts/validate-drills.ts las reverifica
// por fuerza bruta: no se confía en las del prototipo, que calculó otro motor.
import type { SeedAnswer, SeedDrill } from './types';

export const SEED_BLOCKS: Record<'activacion' | 'alcance' | 'seguro' | 'tabla' | 'remate', SeedDrill[]> = {
  activacion: [
    {
      id: 'a1',
      tech: 'alcance',
      type: 'reach',
      map: 'practica',
      T: 2,
      cast: ['Bruno'],
      given: [{ k: 'at', c: 'Bruno', r: 'coc', t: 0 }],
      ask: { c: 'Bruno', t: 1 },
      prompt: '¿Dónde pudo estar Bruno a las 22:00? Toca todas las salas posibles.',
      explain: 'En una hora, Bruno se queda en la Cocina o cruza una sola puerta: al Salón o al Invernadero.',
    },
    {
      id: 'a2',
      tech: 'seguro',
      type: 'tri',
      map: 'practica',
      T: 2,
      cast: ['Celia'],
      given: [{ k: 'at', c: 'Celia', r: 'sal', t: 1 }],
      stmt: { k: 'at', c: 'Celia', r: 'coc', t: 0 },
      explain:
        'Una hora antes, Celia pudo estar en el Salón o en cualquier sala con puerta al Salón: la Biblioteca, la Cocina o el Vestíbulo. La Cocina es posible, pero no segura.',
      show: { rooms: ['sal', 'bib', 'coc', 'ves'] },
    },
    {
      id: 'a3',
      tech: 'alcance',
      type: 'reach',
      map: 'practica',
      T: 2,
      cast: ['Dora'],
      given: [{ k: 'at', c: 'Dora', r: 'inv', t: 1 }],
      ask: { c: 'Dora', t: 0 },
      prompt: '¿Dónde pudo estar Dora a las 21:00, una hora antes? Toca todas las salas posibles.',
      explain: 'Hacia atrás funciona igual: una hora antes, Dora estaba en el Invernadero o en una sala con puerta a él, la Cocina o el Vestíbulo.',
    },
    {
      id: 'a4',
      tech: 'alcance',
      type: 'tri',
      map: 'practica',
      T: 2,
      cast: ['Elías'],
      given: [{ k: 'at', c: 'Elías', r: 'bib', t: 0 }],
      stmt: { k: 'notat', c: 'Elías', r: 'coc', t: 1 },
      explain: 'De la Biblioteca a la Cocina hay dos puertas, pasando por el Salón. En una hora Elías no llega, así que seguro que no estaba en la Cocina.',
      show: { path: ['bib', 'sal', 'coc'] },
    },
    {
      id: 'a5',
      tech: 'alcance',
      type: 'reach',
      map: 'practica',
      T: 1,
      cast: ['Bruno'],
      given: [{ k: 'feat', c: 'Bruno', t: 0, f: 'vent', neg: false }],
      ask: { c: 'Bruno', t: 0 },
      prompt: '¿En qué salas pudo estar Bruno? Fíjate en los iconos del plano.',
      explain: 'Las salas con ventana son el Salón, la Cocina y el Invernadero. La Biblioteca solo tiene chimenea.',
    },
  ],
  alcance: [
    {
      id: 't1a',
      tech: 'alcance',
      type: 'reach',
      map: 'mansion',
      T: 3,
      cast: ['Celia'],
      given: [{ k: 'at', c: 'Celia', r: 'bod', t: 0 }],
      ask: { c: 'Celia', t: 2 },
      prompt: '¿Dónde pudo estar Celia a las 23:00? Son dos horas: hasta dos puertas.',
      explain:
        'A las 22:00, Celia solo pudo estar en la Bodega, el Vestíbulo o el Salón. Desde ahí, a las 23:00 suma el Estudio, el Comedor y la Biblioteca. El Invernadero y la Cocina quedan a tres puertas.',
    },
    {
      id: 't1b',
      tech: 'alcance',
      type: 'reach',
      map: 'mansion',
      T: 3,
      cast: ['Dora'],
      given: [{ k: 'at', c: 'Dora', r: 'inv', t: 2 }],
      ask: { c: 'Dora', t: 1 },
      prompt: 'Dora estaba en el Invernadero a las 23:00. ¿Dónde pudo estar a las 22:00?',
      explain: 'Una hora antes, Dora estaba en el Invernadero o en una sala con puerta a él: el Estudio o el Comedor.',
    },
    {
      id: 't1c',
      tech: 'alcance',
      type: 'reach',
      map: 'mansion',
      T: 3,
      cast: ['Bruno'],
      given: [
        { k: 'at', c: 'Bruno', r: 'com', t: 0 },
        { k: 'at', c: 'Bruno', r: 'est', t: 2 },
      ],
      ask: { c: 'Bruno', t: 1 },
      prompt: 'Bruno estaba en el Comedor a las 21:00 y en el Estudio a las 23:00. ¿Dónde pudo estar a las 22:00?',
      explain:
        'Cruza las dos horas: desde el Comedor pudo ir al Invernadero, el Vestíbulo o la Cocina, o quedarse. Para llegar al Estudio a las 23:00 tenía que estar en una sala con puerta al Estudio. Solo encajan el Invernadero y el Vestíbulo.',
    },
    {
      id: 't1d',
      tech: 'alcance',
      type: 'reach',
      map: 'mansion',
      T: 3,
      cast: ['Elías'],
      given: [
        { k: 'at', c: 'Elías', r: 'ves', t: 1 },
        { k: 'feat', c: 'Elías', t: 2, f: 'chim', neg: false },
      ],
      ask: { c: 'Elías', t: 2 },
      prompt: 'Elías estaba en el Vestíbulo a las 22:00 y a las 23:00 estaba en una sala con chimenea. ¿Dónde pudo estar a las 23:00?',
      explain: 'Desde el Vestíbulo pudo quedarse o ir al Estudio, el Salón, el Comedor o la Bodega. De esas, solo el Salón y el Comedor tienen chimenea.',
    },
    {
      id: 't1e',
      tech: 'alcance',
      type: 'tri',
      map: 'mansion',
      T: 3,
      cast: ['Celia'],
      given: [{ k: 'at', c: 'Celia', r: 'coc', t: 0 }],
      stmt: { k: 'notat', c: 'Celia', r: 'ves', t: 1 },
      explain: 'Desde la Cocina, en una hora Celia solo pudo quedarse o pasar al Comedor. El Vestíbulo está a dos puertas.',
      show: { path: ['coc', 'com', 'ves'] },
    },
  ],
  seguro: [
    {
      id: 't2a',
      tech: 'seguro',
      type: 'tri',
      map: 'practica',
      T: 2,
      cast: ['Celia', 'Dora'],
      given: [
        { k: 'together', a: 'Celia', b: 'Dora', t: 1 },
        { k: 'at', c: 'Dora', r: 'coc', t: 1 },
      ],
      stmt: { k: 'at', c: 'Celia', r: 'coc', t: 1 },
      explain: 'Celia y Dora estaban en la misma sala a las 22:00, y Dora estaba en la Cocina. Así que Celia también, seguro.',
    },
    {
      id: 't2b',
      tech: 'seguro',
      type: 'tri',
      map: null,
      T: 1,
      cast: ['Bruno', 'Celia', 'Dora', 'Elías'],
      objs: ['candelabro', 'cuerda', 'abrecartas', 'veneno'],
      given: [{ k: 'ncarry', c: 'Bruno', o: 'cuerda' }],
      stmt: { k: 'carry', c: 'Bruno', o: 'veneno' },
      explain: 'Que Bruno no llevara la cuerda deja tres objetos posibles para él. El veneno es uno de ellos, pero nada lo demuestra: decir que sí sería una corazonada.',
    },
    {
      id: 't2c',
      tech: 'seguro',
      type: 'tri',
      map: 'practica',
      T: 1,
      cast: ['Bruno', 'Celia', 'Dora'],
      objs: ['candelabro', 'cuerda', 'abrecartas'],
      given: [
        { k: 'cat', o: 'cuerda', r: 'coc', t: 0 },
        { k: 'at', c: 'Bruno', r: 'bib', t: 0 },
      ],
      stmt: { k: 'ncarry', c: 'Bruno', o: 'cuerda' },
      explain: 'Quien llevaba la cuerda estaba en la Cocina a las 21:00, y Bruno estaba en la Biblioteca. No pudo ser él: seguro que no la llevaba.',
    },
    {
      id: 't2d',
      tech: 'seguro',
      type: 'tri',
      map: 'practica',
      T: 2,
      cast: ['Bruno', 'Celia', 'Dora'],
      given: [
        { k: 'count', r: 'sal', t: 1, n: 2 },
        { k: 'at', c: 'Bruno', r: 'sal', t: 1 },
      ],
      stmt: { k: 'at', c: 'Celia', r: 'sal', t: 1 },
      explain: 'En el Salón había dos personas y una era Bruno. La otra pudo ser Celia o Dora: no se puede saber cuál.',
    },
    {
      id: 't2e',
      tech: 'seguro',
      type: 'tri',
      map: 'practica',
      T: 2,
      cast: ['Celia', 'Dora'],
      given: [
        { k: 'apart', a: 'Celia', b: 'Dora' },
        { k: 'at', c: 'Celia', r: 'ves', t: 0 },
      ],
      stmt: { k: 'at', c: 'Dora', r: 'ves', t: 0 },
      explain: 'Celia y Dora no coincidieron nunca. Celia estaba en el Vestíbulo a las 21:00, así que Dora no podía estar allí: es falso.',
    },
  ],
  tabla: [
    {
      id: 't3a',
      tech: 'tabla',
      type: 'pick',
      map: null,
      T: 1,
      cast: ['Bruno', 'Celia', 'Dora'],
      objs: ['candelabro', 'cuerda', 'abrecartas'],
      given: [
        { k: 'ncarry', c: 'Bruno', o: 'cuerda' },
        { k: 'ncarry', c: 'Celia', o: 'cuerda' },
      ],
      ask: { who: 'cuerda' },
      explain: 'Cada objeto lo llevaba alguien. Si ni Bruno ni Celia llevaban la cuerda, la llevaba Dora.',
    },
    {
      id: 't3b',
      tech: 'tabla',
      type: 'pick',
      map: null,
      T: 1,
      cast: ['Bruno', 'Celia', 'Dora'],
      objs: ['candelabro', 'cuerda', 'abrecartas'],
      given: [
        { k: 'ncarry', c: 'Bruno', o: 'candelabro' },
        { k: 'ncarry', c: 'Bruno', o: 'cuerda' },
        { k: 'ncarry', c: 'Dora', o: 'candelabro' },
      ],
      ask: { what: 'Celia' },
      explain: 'A Bruno solo le queda el abrecartas. Dora no lleva el candelabro ni el abrecartas, así que lleva la cuerda. Para Celia queda el candelabro.',
    },
    {
      id: 't3c',
      tech: 'tabla',
      type: 'pick',
      map: 'practica',
      T: 1,
      cast: ['Bruno', 'Celia', 'Elías'],
      objs: ['cuerda', 'abrecartas', 'veneno'],
      given: [
        { k: 'cfeat', o: 'veneno', t: 0, f: 'vent', neg: false },
        { k: 'at', c: 'Elías', r: 'bib', t: 0 },
        { k: 'ncarry', c: 'Bruno', o: 'veneno' },
      ],
      ask: { who: 'veneno' },
      explain: 'Quien llevaba el veneno estaba en una sala con ventana. Elías estaba en la Biblioteca, que no tiene ventana. Bruno tampoco lo llevaba. Queda Celia.',
    },
    {
      id: 't3d',
      tech: 'tabla',
      type: 'pick',
      map: null,
      T: 1,
      cast: ['Bruno', 'Celia', 'Dora'],
      objs: ['candelabro', 'cuerda', 'abrecartas'],
      given: [{ k: 'ncarry', c: 'Bruno', o: 'cuerda' }],
      ask: { who: 'cuerda' },
      explain: 'Bruno queda descartado, pero la cuerda pudo llevarla Celia o Dora. Con esta pista sola no se puede saber.',
    },
    {
      id: 't3e',
      tech: 'tabla',
      type: 'pick',
      map: 'practica',
      T: 2,
      cast: ['Bruno', 'Celia', 'Dora'],
      objs: ['candelabro', 'cuerda', 'abrecartas'],
      given: [
        { k: 'at', c: 'Bruno', r: 'coc', t: 0 },
        { k: 'cat', o: 'cuerda', r: 'bib', t: 1 },
        { k: 'ncarry', c: 'Celia', o: 'cuerda' },
      ],
      ask: { who: 'cuerda' },
      explain:
        'Quien llevaba la cuerda estaba en la Biblioteca a las 22:00. Bruno estaba en la Cocina a las 21:00, a dos puertas: no llega. Celia tampoco la llevaba. La llevaba Dora.',
      show: { path: ['coc', 'sal', 'bib'] },
    },
  ],
  remate: [
    {
      id: 'r1',
      tech: 'remate',
      type: 'clue',
      map: 'practica',
      T: 2,
      rv: 'bib',
      td: 1,
      cast: ['Bruno', 'Celia', 'Dora', 'Elías'],
      objs: ['candelabro', 'cuerda', 'abrecartas', 'veneno'],
      context: 'La víctima apareció en la Biblioteca a las 22:00. Ya descartaste a Bruno y a Celia: quedan Dora y Elías.',
      clues: [
        { k: 'at', c: 'Bruno', r: 'inv', t: 0, used: true },
        { k: 'at', c: 'Celia', r: 'sal', t: 1, used: true },
        { k: 'at', c: 'Dora', r: 'coc', t: 0 },
        { k: 'ncarry', c: 'Elías', o: 'veneno' },
        { k: 'count', r: 'ves', t: 1, n: 0 },
      ],
      decide: { culprit: true },
      prompt: '¿Qué pista decide entre Dora y Elías?',
      explain:
        'Dora estaba en la Cocina a las 21:00, a dos puertas de la Biblioteca. No pudo estar con la víctima a las 22:00: el culpable es Elías. La pista ya la tenías; solo había que mirarla pensando en esos dos.',
      show: { path: ['coc', 'sal', 'bib'] },
    },
    {
      id: 'r2',
      tech: 'remate',
      type: 'contra',
      map: 'practica',
      T: 2,
      rv: 'bib',
      td: 1,
      cast: ['Bruno', 'Celia', 'Dora', 'Elías'],
      objs: ['candelabro', 'cuerda', 'abrecartas', 'veneno'],
      context: 'La víctima apareció en la Biblioteca a las 22:00. Quedan Celia y Elías. Prueba una hipótesis: supón que fue Celia.',
      hyp: { culprit: 'Celia' },
      tokens: [{ c: 'Celia', r: 'bib', h: '22:00' }],
      clues: [
        { k: 'at', c: 'Celia', r: 'sal', t: 0 },
        { k: 'together', a: 'Celia', b: 'Bruno', t: 1 },
        { k: 'ncarry', c: 'Celia', o: 'candelabro' },
        { k: 'at', c: 'Dora', r: 'ves', t: 1 },
      ],
      prompt: 'Si Celia hubiera estado a solas con la víctima, ¿qué pista se rompe?',
      explain:
        'A las 22:00, Celia y Bruno estaban en la misma sala. Si Celia estaba en la Biblioteca, Bruno también, y la culpable no habría estado sola. La hipótesis falla: no fue Celia. Probar cada candidato y buscar dónde se rompe es la mejor salida cuando te quedan dos.',
    },
    {
      id: 'r3',
      tech: 'remate',
      type: 'clue',
      map: 'practica',
      T: 2,
      cast: ['Bruno', 'Celia', 'Dora', 'Elías'],
      objs: ['candelabro', 'cuerda', 'abrecartas', 'veneno'],
      context: 'Ya sabes que Elías es el culpable y que estaba en la Biblioteca a las 22:00. En la tabla solo le quedan dos objetos: la cuerda y el veneno.',
      facts: [{ k: 'at', c: 'Elías', r: 'bib', t: 1 }],
      clues: [
        { k: 'ncarry', c: 'Elías', o: 'candelabro', used: true },
        { k: 'ncarry', c: 'Elías', o: 'abrecartas', used: true },
        { k: 'cfeat', o: 'veneno', t: 1, f: 'vent', neg: false },
        { k: 'at', c: 'Bruno', r: 'coc', t: 0 },
        { k: 'ncarry', c: 'Celia', o: 'cuerda' },
      ],
      decide: { what: 'Elías' },
      prompt: '¿Qué pista decide el arma?',
      explain:
        'Quien llevaba el veneno estaba en una sala con ventana a las 22:00, y Elías estaba en la Biblioteca, que solo tiene chimenea. No llevaba el veneno: el arma es la cuerda.',
    },
  ],
};

/** Respuestas del prototipo (GYM_ANS), pasadas de índices a forma de autor. */
export const SEED_ANSWERS: Record<string, SeedAnswer> = {
  a1: { type: 'reach', rooms: ['sal', 'coc', 'inv'] },
  a2: { type: 'tri', value: 'NS' },
  a3: { type: 'reach', rooms: ['coc', 'ves', 'inv'] },
  a4: { type: 'tri', value: 'V' },
  a5: { type: 'reach', rooms: ['sal', 'coc', 'inv'] },
  t1a: { type: 'reach', rooms: ['bib', 'est', 'sal', 'ves', 'com', 'bod'] },
  t1b: { type: 'reach', rooms: ['est', 'inv', 'com'] },
  t1c: { type: 'reach', rooms: ['inv', 'ves'] },
  t1d: { type: 'reach', rooms: ['sal', 'com'] },
  t1e: { type: 'tri', value: 'V' },
  t2a: { type: 'tri', value: 'V' },
  t2b: { type: 'tri', value: 'NS' },
  t2c: { type: 'tri', value: 'V' },
  t2d: { type: 'tri', value: 'NS' },
  t2e: { type: 'tri', value: 'F' },
  t3a: { type: 'pick', value: 'Dora' },
  t3b: { type: 'pick', value: 'candelabro' },
  t3c: { type: 'pick', value: 'Celia' },
  t3d: { type: 'pick', value: 'NS' },
  t3e: { type: 'pick', value: 'Dora' },
  r1: { type: 'decide', decide: [2], answer: 'Elías' },
  r2: { type: 'decide', decide: [1] },
  r3: { type: 'decide', decide: [2], answer: 'cuerda' },
};

export const SEED_DRILLS: SeedDrill[] = Object.values(SEED_BLOCKS).flat();
